// Run with NODE_PATH pointing to the existing runtime's node_modules; no added dependencies.
import {createRequire} from 'node:module';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {dirname, join} from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require('playwright');
const root=dirname(fileURLToPath(import.meta.url));
const server=createServer(async(req,res)=>{try{const p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const ext=p.split('.').pop();res.setHeader('Content-Type',({js:'text/javascript',css:'text/css',woff2:'font/woff2'})[ext]||'text/html');res.end(await readFile(join(root,p==='/'?'index.html':p)));}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{})});
const results=[];
async function run(name,fn){const page=await browser.newPage({viewport:{width:1440,height:1120}});page.setDefaultTimeout(4000);const errors=[];page.on('pageerror',e=>errors.push(e.message));try{await page.goto(url+'/#login');await fn(page);assert.deepEqual(errors,[]);results.push({name,status:'pass'});}catch(e){results.push({name,status:'fail',error:e.message});}finally{await page.close();}}
async function login(page,role='business'){await page.locator(`[data-role="${role}"]`).click();await page.locator('#login-email').fill(role==='service'?'operator@example.com':'cafe@example.com');await page.locator('#login-password').fill('JejuDemo26!');await page.locator('#login-form button[type=submit]').click();await page.waitForURL('**/#overview');}
async function go(page,hash){await page.goto(url+'/#'+hash);}
async function blockWrites(page,key){await page.evaluate(key=>{const original=Storage.prototype.setItem;window.restoreStorage=()=>Storage.prototype.setItem=original;Storage.prototype.setItem=function(k,v){if(k===key)throw new DOMException('Storage unavailable','QuotaExceededError');return original.call(this,k,v);};},key);}
await run('Removed ontology and demo actions cannot be entered; required evidence stays reachable',async p=>{await login(p);await go(p,'ontology');await p.waitForURL('**/#overview');assert.equal(new URL(p.url()).hash,'#overview');assert.equal(await p.locator('a[href="#ontology"],[data-action="agent"],[data-action="fill-demo"],[data-action="enter"]').count(),0);await go(p,'recommendations');assert.equal(await p.locator('.optional-feature').count(),0);await p.locator('[data-evidence]').first().click();assert.match(await p.locator('#dialog').innerText(),/출처|자료/);await p.locator('[data-action="source"]').click();assert.match(await p.locator('#dialog').innerText(),/단위 만 명/);});
await run('Logout cancel preserves active role; confirmation ends session and requires login screen',async p=>{await login(p);await p.locator('.profile').click();assert.equal(await p.locator('#dialog').getAttribute('open'),'');await p.locator('#dialog').getByRole('button',{name:'취소',exact:true}).click();assert.equal(new URL(p.url()).hash,'#overview');await p.locator('.sidebar-session').click();await p.locator('[data-action="confirm-logout"]').click();await p.waitForURL('**/#login');assert.equal(await p.evaluate(()=>sessionStorage.getItem('jeju-design-demo-session-v1')),null);assert.equal(await p.locator('[data-action="fill-demo"],[data-action="enter"]').count(),0);});
await run('Saved recommendation threshold filters actual cards and evidence reflects saved rationale',async p=>{await login(p,'service');await go(p,'data');await p.locator('[data-action="criteria"]').click();await p.locator('#criteria-threshold').fill('100');await p.locator('#criteria-form button[type=submit]').click();await go(p,'recommendations');assert.equal(await p.locator('.recommendation').count(),0);assert.match(await p.locator('#main').innerText(),/조건에 맞는 제안이 없습니다/);await go(p,'data');await p.locator('[data-action="criteria"]').click();await p.locator('#criteria-threshold').fill('0');await p.locator('#criteria-reason').fill('지역별 감소율을 확인한 운영자 판단');await p.locator('#criteria-source').fill('검증 자료 v2 · 2025년 월별 방문 · 만 명');await p.locator('#criteria-condition').fill('상품 재고 확인 후 적용');await p.locator('#criteria-form button[type=submit]').click();await go(p,'recommendations');assert.equal(await p.locator('.recommendation').count(),3);await p.locator('[data-evidence]').first().click();const t=await p.locator('#dialog').innerText();assert.match(t,/지역별 감소율을 확인한 운영자 판단/);assert.match(t,/검증 자료 v2/);assert.match(t,/상품 재고 확인 후 적용/);});
await run('Recommendation criterion write failure retains previous criteria and entered values',async p=>{await login(p,'service');await go(p,'data');await p.locator('[data-action="criteria"]').click();await blockWrites(p,'jeju-design-admin-v1');await p.locator('#criteria-threshold').fill('100');await p.locator('#criteria-form button[type=submit]').click();assert.equal(await p.locator('#criteria-threshold').inputValue(),'100');assert.equal(await p.locator('#criteria-error').isVisible(),true);await p.locator('#dialog').getByRole('button',{name:'취소',exact:true}).click();await p.evaluate(()=>window.restoreStorage());await p.locator('[data-action="criteria"]').click();assert.equal(await p.locator('#criteria-threshold').inputValue(),'20');});
await run('CSV validation gates registration, metadata edits invalidate success and invalid rows cannot register',async p=>{await login(p,'service');await go(p,'data');assert.equal(await p.locator('[data-action="csv-sample"],[data-action="csv-sample-invalid"]').count(),0);const valid='region_code,month,value,unit,provider,aggregation\n50110253,2025-10,51,만 명,화면 시안 제작팀,월별 지역 집계';await p.locator('#csv-file').setInputFiles({name:'visits.csv',mimeType:'text/csv',buffer:Buffer.from(valid)});await p.locator('[data-action="validate"]').click();assert.equal(await p.locator('[data-action="csv-register"]').isEnabled(),true);await p.locator('#csv-source').fill('검증 자료 v2');assert.equal(await p.locator('[data-action="csv-register"]').isDisabled(),true);await p.locator('[data-action="validate"]').click();await p.locator('[data-action="csv-register"]').click();assert.match(await p.locator('#csv-status').innerText(),/등록했습니다/);assert.match(await p.locator('.criteria-toolbar').innerText(),/등록한 자료 1개/);assert.match(await p.locator('#toast.visible').innerText(),/자료를 등록했습니다/);assert.equal(await p.locator('[data-action="csv-register"]').isDisabled(),true);await p.locator('#csv-file').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from(valid.replace(',51,',',,'))});await p.locator('[data-action="validate"]').click();assert.equal(await p.locator('[data-action="csv-register"]').isDisabled(),true);assert.match(await p.locator('#csv-validation').innerText(),/누락값 · 확인 필요/);});
await run('Deleting a plan cancels safely, rolls back on failed persistence and retries successfully',async p=>{await login(p);await go(p,'calendar');await p.locator('[data-edit="sample-oct"]').click();await p.locator('[data-delete]').click();await p.locator('#dialog').getByRole('button',{name:'취소',exact:true}).click();assert.equal(await p.locator('.plan-item').count(),2);if(await p.locator('#plan-form').count())await p.locator('#dialog').getByRole('button',{name:'취소',exact:true}).click();await p.locator('[data-edit="sample-oct"]').click();await p.locator('[data-delete]').click();await blockWrites(p,'jeju-design-prototype-v1');await p.locator('[data-confirm-delete]').click();assert.equal(await p.locator('.plan-item').count(),2);assert.equal(await p.locator('#delete-error').isVisible(),true);await p.evaluate(()=>window.restoreStorage());await p.locator('[data-confirm-delete]').click();assert.equal(await p.locator('.plan-item').count(),1);await p.reload();assert.equal(await p.locator('.plan-item').count(),1);});
await run('CSV management downloads a template that the registration validator accepts',async p=>{await login(p,'service');await go(p,'data');const downloadPromise=p.waitForEvent('download');await p.locator('[data-action="export"]').click();const download=await downloadPromise;const bytes=await readFile(await download.path());await p.locator('#csv-file').setInputFiles({name:'template.csv',mimeType:'text/csv',buffer:bytes});await p.locator('[data-action="validate"]').click();assert.equal(await p.locator('[data-action="csv-register"]').isEnabled(),true);});
await run('Overview keeps schedule summary and opens full proposal details from its compact card',async p=>{await login(p);await p.locator('.timeline-panel').waitFor();assert.match(await p.locator('.timeline-panel').innerText(),/10월/);assert.match(await p.locator('.timeline-panel').innerText(),/11월/);await p.getByRole('link',{name:'제안 상세보기',exact:true}).first().click();await p.locator('.proposal-fields').first().waitFor();assert.equal(new URL(p.url()).hash,'#recommendations');await p.locator('[data-evidence]').first().click();assert.match(await p.locator('#dialog').innerText(),/출처·기준/);});
await browser.close();server.close();console.log(JSON.stringify(results,null,2));if(results.some(r=>r.status==='fail'))process.exitCode=1;
